version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: revcart_db
    networks:
      - revcart-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: revcart-backend
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/revcart_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      FRONTEND_URL: http://16.112.117.45:3000
      CORS_ORIGINS: http://16.112.117.45:3000,http://16.112.117.45:8080
      OAUTH_REDIRECT_URI: http://16.112.117.45:8080/api/login/oauth2/code/google
    ports:
      - "8080:8080"
    networks:
      - revcart-network

  frontend:
    build: ./revcart-frontend
    container_name: revcart-frontend
    depends_on:
      - backend
    ports:
      - "3000:80"
    networks:
      - revcart-network

networks:
  revcart-network:
    driver: bridge
